{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GB",
  "modelName": "iPhone XS",
  "productId": "A0PX",
  "orderSeq": "9",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GB",
  "modelName": "iPhone XS",
  "productId": "A0PX",
  "orderSeq": "9",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GB",
  "modelName": "iPhone XS",
  "productId": "A0PX",
  "orderSeq": "9",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GB",
  "modelName": "iPhone XS",
  "productId": "A0PX",
  "orderSeq": "9",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GB",
  "modelName": "iPhone XS",
  "productId": "A0PX",
  "orderSeq": "9",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GB",
  "modelName": "iPhone XS",
  "productId": "A0Q3",
  "orderSeq": "6",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GB",
  "modelName": "iPhone XS",
  "productId": "A0Q3",
  "orderSeq": "6",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GB",
  "modelName": "iPhone XS",
  "productId": "A0Q3",
  "orderSeq": "6",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GB",
  "modelName": "iPhone XS",
  "productId": "A0Q3",
  "orderSeq": "6",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GB",
  "modelName": "iPhone XS",
  "productId": "A0Q3",
  "orderSeq": "6",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "3",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GB",
  "modelName": "iPhone XS",
  "productId": "A0Q4",
  "orderSeq": "3",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "3",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GB",
  "modelName": "iPhone XS",
  "productId": "A0Q4",
  "orderSeq": "3",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "3",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GB",
  "modelName": "iPhone XS",
  "productId": "A0Q4",
  "orderSeq": "3",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "3",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GB",
  "modelName": "iPhone XS",
  "productId": "A0Q4",
  "orderSeq": "3",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "3",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GB",
  "modelName": "iPhone XS",
  "productId": "A0Q4",
  "orderSeq": "3",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "262529",
  "tkeyColorCd": "20",
  "colorName": "스페이스 그레이",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "3",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GW",
  "modelName": "iPhone XS",
  "productId": "A0QU",
  "orderSeq": "7",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "8",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "4",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GW",
  "modelName": "iPhone XS",
  "productId": "A0QU",
  "orderSeq": "7",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "8",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "4",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GW",
  "modelName": "iPhone XS",
  "productId": "A0QU",
  "orderSeq": "7",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "8",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "4",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GW",
  "modelName": "iPhone XS",
  "productId": "A0QU",
  "orderSeq": "7",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "8",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "4",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GW",
  "modelName": "iPhone XS",
  "productId": "A0QU",
  "orderSeq": "7",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "8",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "4",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GG",
  "modelName": "iPhone XS",
  "productId": "A0QX",
  "orderSeq": "8",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "12",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "6",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GG",
  "modelName": "iPhone XS",
  "productId": "A0QX",
  "orderSeq": "8",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "12",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "6",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GG",
  "modelName": "iPhone XS",
  "productId": "A0QX",
  "orderSeq": "8",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "12",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "6",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GG",
  "modelName": "iPhone XS",
  "productId": "A0QX",
  "orderSeq": "8",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "12",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "6",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_64GG",
  "modelName": "iPhone XS",
  "productId": "A0QX",
  "orderSeq": "8",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "891000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "64G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "12",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "6",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GW",
  "modelName": "iPhone XS",
  "productId": "A0R7",
  "orderSeq": "4",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GW",
  "modelName": "iPhone XS",
  "productId": "A0R7",
  "orderSeq": "4",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GW",
  "modelName": "iPhone XS",
  "productId": "A0R7",
  "orderSeq": "4",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GW",
  "modelName": "iPhone XS",
  "productId": "A0R7",
  "orderSeq": "4",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GW",
  "modelName": "iPhone XS",
  "productId": "A0R7",
  "orderSeq": "4",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "6",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "2",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GG",
  "modelName": "iPhone XS",
  "productId": "A0R8",
  "orderSeq": "5",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "2",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GG",
  "modelName": "iPhone XS",
  "productId": "A0R8",
  "orderSeq": "5",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "2",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GG",
  "modelName": "iPhone XS",
  "productId": "A0R8",
  "orderSeq": "5",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "2",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GG",
  "modelName": "iPhone XS",
  "productId": "A0R8",
  "orderSeq": "5",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "2",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_256GG",
  "modelName": "iPhone XS",
  "productId": "A0R8",
  "orderSeq": "5",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "940500",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "256G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "2",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GW",
  "modelName": "iPhone XS",
  "productId": "A0R9",
  "orderSeq": "1",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "0",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GW",
  "modelName": "iPhone XS",
  "productId": "A0R9",
  "orderSeq": "1",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "0",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GW",
  "modelName": "iPhone XS",
  "productId": "A0R9",
  "orderSeq": "1",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "0",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GW",
  "modelName": "iPhone XS",
  "productId": "A0R9",
  "orderSeq": "1",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "0",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GW",
  "modelName": "iPhone XS",
  "productId": "A0R9",
  "orderSeq": "1",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "E4E4E2",
  "tkeyColorCd": "10",
  "colorName": "실버",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "0",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GG",
  "modelName": "iPhone XS",
  "productId": "A0RA",
  "orderSeq": "2",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "0",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "5",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GG",
  "modelName": "iPhone XS",
  "productId": "A0RA",
  "orderSeq": "2",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "12",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "5",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GG",
  "modelName": "iPhone XS",
  "productId": "A0RA",
  "orderSeq": "2",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "5",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GG",
  "modelName": "iPhone XS",
  "productId": "A0RA",
  "orderSeq": "2",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "24",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "5",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "24",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
{
  "productGrpId": "000003292",
  "productGrpNm": "iPhone XS",
  "modelNo": "IPHONE_XS_512GG",
  "modelName": "iPhone XS",
  "productId": "A0RA",
  "orderSeq": "2",
  "saleCd": "04",
  "entryCd": "31",
  "entryNm": "기기변경",
  "commitmentTerm": "24",
  "commitmentCd": "01",
  "installmentTerm": "30",
  "productPrice": "990000",
  "priceSbs": null,
  "subscriptionId": "NA00005134",
  "pcSaleCd": "01",
  "phoneCapacity": "512G",
  "colorSeq": "001",
  "colorHex": "FADCC2",
  "tkeyColorCd": "6B",
  "colorName": "골드",
  "stock": "0",
  "saftyStock": "10",
  "stockNotiYn": "N",
  "jobStatus": "40",
  "o2oYn": "N",
  "o2oStockCount": "5",
  "reserveYn": "N",
  "newInstallmentYn": "N",
  "o2oRsvStockCount": "0",
  "prodRentalYn": "N",
  "rentalYn": null,
  "eqprentPlanId": null,
  "rentalAllotMthCnt": "0",
  "rentalCntrctMthCnt": "0",
  "mthRentDcAmt": "0",
  "addMthRentDcAmt": "0",
  "trentalO2oYn": null,
  "displayAreaCounsel": "Y",
  "callYn": "Y",
  "chtYn": "Y",
  "kkoYn": "Y",
  "quickStock": "0",
  "error": {
    "code": "00",
    "message": ""
  }
}
